name: PR
run-name: ${{ github.actor }}  ${{ github.event_name }} event on ${{ github.name }}ğŸš€
on:
  pull_request:
    branches:
      - main
jobs:
  premerge:
    runs-on: ubuntu-latest
    steps:
      - run: npm run prepush
