name: Push
run-name: ${{ github.actor }}  ${{ github.event_name }} event on ${{ github.name }}ðŸš€
on: push
jobs:
  prepush:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, build, test
        run: |
          npm install
          npm run precommit
